### ISSUE TITLE
Add warning that use of GPL3 for modules is viral for workflows

### ISSUE THREAD

**Issue by stain** [watchdog-wms/watchdog-wms-modules#89]
As these modules are provided under the [GNU GPL 3](https://github.com/watchdog-wms/watchdog-wms-modules/blob/master/LICENSE) license, it is my understanding this means any workflow built using them also need to be license GPLv3 (if distributed).

As Watchdog WMS modules are declared in XML Schema, which is then used from within a workflow XML file, they can be considered equivalent to "interface definition files" above.

In particular, such workflows can't run without the corresponding module definitions, as they contain the command line to run, etc. 

So if a third-party use watchdog-wms-modules to create their workflow, they would be creating a new _combined work_ based on the modules, and so their workflow would - if it was to be distributed on its own - need to be released under the GPLv3 license as well. 

See https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

Note that the GPL-3 license of Watchdog engine itself is not "viral" in the same sense, because it can be seen as an "interpreter" of workflows. In particular, the workflows do not do any "call backs" to Watchdog code. 

See https://www.gnu.org/licenses/gpl-faq.en.html#IfInterpreterIsGPL

On the other hand, a Watchdog workflow has "calls" to the functions of the 
watchdog-wms-modules and is thus forming a combined work.

I think either the README should have a warning about this, or I would recommend changing the license of https://github.com/watchdog-wms/watchdog-wms-modules to a softer license like LGPL 3.0 or Apache License 2.0

See https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense

**Comment by klugem** [comment]
> I think either the README should have a warning about this, or I would recommend changing the license of https://github.com/watchdog-wms/watchdog-wms-modules to a softer license like LGPL 3.0 or Apache License 2.0

I would prefer to change the licence to Apache License 2.0. However, another reviewer suggested to allow individual licences per module. I think this might be appropriate in some cases as some modules might contain more advanced code apart from the XML definition file.

Hence, I would add a notice in the README file that all modules are licenced according to Apache License 2.0 if not otherwise stated in the module folder.

@stain What do you think about that approach?

**Comment by klugem** [comment]
Closed with d9ccf62029ff27a1a9451a093a410c2351c75502, 4364f5efbb57a692e0f9ef0dc9a8692dce0df4f8, and eda32351d8ef8459499bfdb6eeb4553623ccacee.
